### PR TITLE
[JENKINS-66606] Add support for the Jenkins JUnit flaky-test-handler plugin

### PR DESCRIPTION
**Pull request by marcjay**
[JENKINS-66606](https://issues.jenkins.io/browse/JENKINS-66606) Add support for the Jenkins JUnit flaky-test-handler plugin

- Add optional dependency on flaky-test-handler (https://plugins.jenkins.io/flaky-test-handler/)
- If the Flaky Test Handler plugin is installed, add it as a TestDataPublisher to JUnit
- Update unit tests to support the plugin processing the JUnit test results

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by marcjay** [comment]
### Test evidence
Ran the following Jenkins pipeline without the Flaky Test Handler plugin installed:
```
node {
  stage ('Build') {
    git url: 'https://github.com/cyrille-leclerc/multi-module-maven-project'
    withMaven {
      sh "mvn clean verify"
    } // withMaven will discover the generated Maven artifacts, JUnit Surefire & FailSafe reports and FindBugs reports
  }
}
```
image
Shows a standard message about the plugin not being installed, with a hyperlink to the plugin page

I forked the multi-module-maven-project project, enabled Surefire, set the rerunFailingTestsCount property to 10 and added a flaky test to it: https://github.com/marcjay/multi-module-maven-project/commit/3ac86d15ba4fda180b766bc5463eef796e09bd37

I then re-ran the pipeline, using https://github.com/marcjay/multi-module-maven-project and confirmed that flaky tests were being picked up by Flaky Test Handler plugin:
image
image
image
image

**Comment by aheritier** [comment]
Thanks a lot for this contribution @marcjay 
I am discovering this plugin, I didn't know it.
Your implementation and tests are looking good.
The only thing that should be added is a description in the README

**Comment by marcjay** [comment]
@aheritier Many thanks! README updated

**Review by aheritier — APPROVED** [review]
will be released in version 3.11.0

**Comment by aheritier** [comment]
@bguerin Now that I merged it (but not yet released) I have a doubt if it should be in the same published or in a different one (I can split it, it's not a problem cc @marcjay )

The point is that we are processing the same files (tests results) thus it makes sense to have 1 publisher but we have 2 optional plugins integrated (https://plugins.jenkins.io/junit-attachments/[JUnit Attachments] and/or https://plugins.jenkins.io/flaky-test-handler/[Flaky Test Handler]). 

I am afraid to get a request in the future to disable only one of them like we had in #344 and then only the full publisher can be disabled (both or nothing). WDYT ?

**Comment by bguerin** [comment]
I think about single responsability. A publisher should do only one thing, thus integrate only one plugin

The actual JUnitPublisher should be splited in two, one for JUnit reports, and one for attachments, maybe having a superclass in common, to share some utility methods to handle spy results

**Comment by aheritier** [comment]
@bguerin it makes sense. For new code it's not difficult to create a new publisher, I'll do it
For the existing code, like for #344 what I am not sure is how to handle the deprecation/migration process of publishers...

**Comment by bguerin** [comment]
Same here. I think we have to discover / check / hard test this when doing the first, like #344.
Maybe for now we can open another issue to remember to split JUnitPublisher as well

**Comment by aheritier** [comment]
ok I will take that path:
1/ Move the new flaky integration to a dedicated publisher ( FYI @marcjay )
2/ Create a followup jira issue like I did for #344 to not forget to split the existing junit publisher in 2

**Comment by marcjay** [comment]
I 100% agree that things should be split up where possible. Just that with this, as these are test data publishers which are linked to JUnit, is it possible to have these as separate publishers without JUnit re-processing the test results, ending up with duplicated results?

**Comment by aheritier** [comment]
not yet sure @marcjay 
It's effectively critical/required to not have duplicated results.
I have to verify the implementation

**Pull request merged**
