### PR TITLE
Use database version from bom and include specific MariaDB driver

### PR DESCRIPTION
**Pull request by jonesbusy**
Perhaps the PR should be split

- Increase core version (I think with the recent 2.440.1 is worth to use 2.414 which is the recommended version for the bom
- Use version from bom for existing drivers
- Include specific MariaDB driver using mariadb-api plugin 

What's your though about it @bguerin ?

Thanks

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by bguerin** [comment]
Thanks for you work !

I am currently switching to 2.401.x baseline, and will switch to 2.414.x right after to catch the train
Doing this, I will remove versions informations if duplicated from the BOM

So, for the remaining specific MariaDB stuff, this should, for now, be handled by the MySQL Dao, whici accept both Mysql and Maria, reading version from both and loading the appropriate driver (if I remember well)
I am not against separating the two and having a MysqlDao dealing only with Mysql, and a Maria one dealing only with Maria, but this case would need more changes and specific tests too

**Comment by jonesbusy** [comment]
Thanks. Well I will probably wait that the plugin is built for the 2.414 baseline.

I will see what is the best, but I think the current implementation that doesn't use the database plugin is not supporting the mariadb:// scheme.

If it's too much effort probably better to wait Integration with database plugin.

**Comment by bguerin** [comment]
> Integration with database plugin

another hot subject I really want to do ;)

**Comment by jonesbusy** [comment]
> another hot subject I really want to do ;)

Yea I know 😄  Same here

**Comment by jonesbusy** [comment]
Closing for now, I don't have time in the next months to work on this

**Pull request closed without merging**
