### PR TITLE
Enable CD releases

### PR DESCRIPTION
**Pull request by aheritier**
https://www.jenkins.io/doc/developer/publishing/releasing-cd/

Requires https://github.com/jenkins-infra/repository-permissions-updater/pull/2608/files

(Already merged but not build because ci.jenkins.io down)

Before merging we have to check that the credentials are defined : https://www.jenkins.io/doc/developer/publishing/releasing-cd/#enable-cd-permissions

cc @bguerin @alecharp

### CODE REVIEW

**Review by alecharp — APPROVED** [review]
Looks good to me

**Comment by bguerin** [comment]
YOUHOU !!!!

**Review by bguerin — APPROVED** [review]

**Comment by bguerin** [comment]
@aheritier could you please fix the conflict on the POM. Github propose me a "resolve conflicts" interface but it does not load :(

**Comment by aheritier** [comment]
Done @bguerin

**Pull request merged**
