### PR TITLE
[FIX JENKINS-40142]  - Correctly set default values for String params

### PR DESCRIPTION
**Pull request by alvarolobato**
https://issues.jenkins-ci.org/browse/JENKINS-40142

@reviewbybees

### CODE REVIEW

**Comment by amuniz** [comment]
:bee:

**Comment by cyrille-leclerc** [comment]
🐝

**Comment by amuniz** [comment]
Maybe a `configRoundTrip` test would be desired.

**Comment by alvarolobato** [comment]
@reviewbybees done

**Pull request merged**
