### PR TITLE
JENKINS-46313: Avoid excessive triggering of downstream jobs

### PR DESCRIPTION
**Pull request by markusdlugi**
[JENKINS-46313](https://issues.jenkins-ci.org/browse/JENKINS-46313): Implements two features from the old Maven project type which help to avoid excessive triggering of downstream jobs.

### CODE REVIEW

**Comment by bernardoVale** [comment]
Please merge this :D

**Comment by cyrille-leclerc** [comment]
@bernardoVale we are working at it. We got burned by [JENKINS-47823](https://issues.jenkins-ci.org/browse/JENKINS-47823) that consumed a substantial amount of unplanned work and we are discussing an architectural question on https://issues.jenkins-ci.org/browse/JENKINS-46368?focusedCommentId=321040&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-321040

**Comment by markusdlugi** [comment]
@bernardoVale Haha, soon :)
As @cyrille-leclerc wrote, we are currently still discussing [JENKINS-46368](https://issues.jenkins-ci.org/browse/JENKINS-46368), which will most likely affect this PR. Additionally, I'd first merge [PR#110](https://github.com/jenkinsci/pipeline-maven-plugin/pull/110) before this one, otherwise triggering might not work correctly for multi-module projects. If you really require this feature, I recommend you to cherry-pick the commits from this PR and PR#110 and build the plugin yourself using `mvn clean verify -DskipTests`.

**Comment by dcendents** [comment]
I'd be careful with running this in production. I've been running a custom build of PRs 109 and 110 for a while and I noticed sometimes a build is not triggered when it should.

So I have 2 multi-modules projects.

A
 - A1
 - A2

B
 - B1
 - B2

Let's say that B1 is using A1. After A is built I see "Not triggering B because it has dependencies in the downstream project list". But nothing else is using either A or B.

This is quite basic so it seems odd this would not work. I have other similar multi-module projects where the dependency chain goes over 3 or 4 projects and these work fine though.

**Comment by markusdlugi** [comment]
@dcendents Thanks for testing this. Please note that I added another commit to PR 110 on November 20th because there was a bug in the code, which might cause the behaviour you described. Can you check whether that commit was already present in your custom build? If not, would you mind re-building with that commit in place and report back? You would have to run all related Jenkins jobs once to ensure that the dependencies are updated.

We are running a custom build of both PRs in our production Jenkins instance since a couple of weeks, and for us it is working without issues.

**Comment by dcendents** [comment]
@markusdlugi I built the plugin on November 22nd so I had that commit but still saw the issue I described. If I get some time I'll try to install it on a test server and debug the problem to let you know what I find.

**Comment by markusdlugi** [comment]
@dcendents I see. That would be great, thanks for the effort.

Normally, the plugin should always trigger at least one job. If it doesn't, the only way I can imagine this happening is that your project A consumes one of the artifacts it generated by itself. It will then record itself as a downstream project, and therefore not trigger anything (because it can't trigger itself). Usually, that should be avoided by the changes in PR 110, but seems like there is some artifact which is slipping through and still being recorded as dependency even though it was generated during the build. Would be cool if you could find out which one it is and why it's not detected.

To ensure this doesn't happen, I added another commit to this PR which removes the current project entirely from the downstream pipelines. So even if a dependency to a project itself is recorded, it doesn't have any effect, i.e., this PR should now be independent of PR 110. Your testing would still be appreciated for PR 110, though, because it covers some additional use cases (especially multi branch pipelines).

**Comment by cyrille-leclerc** [comment]
Thanks you very much @markusdlugi and @dcendents to iterate on this new feature. 

Regarding the prioritization, I'll fix the regression introduced by 3.0.3 on space chars in pipeline names before merging new features. I hope to have time to fix this regression by the end of the weekend.

**Comment by dcendents** [comment]
@markusdlugi I tried to reproduce the problem I reported today but couldn't (same plugin build as when I reported it). So I'm not sure what it was.

I've just done a custom build of pipeline-maven-plugin 3.0.5 + PRs 109 and 110. I've added a new logger in jenkins and I'll keep an eye on it to spot anything unusual. I'll let you know if I see anything weird. But so far it works great, without #109 our jenkins server crumbles under the load with excessive job triggering.

**Comment by markusdlugi** [comment]
@dcendents Okay, thanks for your efforts. Good to hear it's working for you :)

There seems to be a merge conflict now, and this PR will need further adjustments after #107 is merged. I'll update it once that has happened.

**Comment by cyrille-leclerc** [comment]
Sorry for the merge conflict @markusdlugi.

**Comment by markusdlugi** [comment]
As mentioned in #110, I resolved the merge conflicts in this PR as well and adjusted it so that it also works with parent project dependencies. I tested it in our production Jenkins instance, and it is working fine. So in my opinion it is mergeable.

**Pull request merged**
