### PR TITLE
JENKINS-57324 Fix '%' char escaping in the windows batch script wrapper for mvn.cmd

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
JENKINS-57324 Fix '%' char escaping in the windows batch script wrapper for mvn.cmd

### CODE REVIEW

**Comment by marioja** [comment]
Is it possible to test this fix before the merge?

**Comment by cyrille-leclerc** [comment]
@marioja I would love to have people helping with testing as I don't have a windows environment available easily.
* Did you identify a risk of regression?
* Could you test? If yes, could you just compile the plugin from the source with "mvn package -DskipTests"

**Comment by marioja** [comment]
@cyrille-leclerc I did compile from the branch, manually installed it and ran it.  It worked perfectly.  In JENKINS-57324 I identified the risk that if this code runs on linux it will fail so if the code you added only runs for windows then I guess it is ok.  I will leave it on my Jenkins box and do more testing but I do not envisage any problem, especially with what I understand the fix to be.

**Comment by cyrille-leclerc** [comment]
> I identified the risk that if this code runs on linux it will fail so if the code you added only runs for windows then I guess it is ok.

The code change is specific to windows build agents:

```java
        if (isUnix) { // Linux, Unix, MacOSX
            String lineSep = "\n";
            script.append("#!/bin/sh -e").append(lineSep);
            script.append("echo ----- withMaven Wrapper script -----").append(lineSep);
            script.append("\"" + mvnExec.getRemote() + "\" " + mavenConfig + " \"$@\"").append(lineSep);

        } else { // Windows
            String lineSep = "\r\n";
            script.append("@echo off").append(lineSep);
            script.append("echo ----- withMaven Wrapper script -----").append(lineSep);
            // JENKINS-57324 escape '%' as '%%'. See https://en.wikibooks.org/wiki/Windows_Batch_Scripting#Quoting_and_escaping
            mavenConfig = mavenConfig.replace("%", "%%");
            script.append("\"" + mvnExec.getRemote() + "\" " + mavenConfig + " %*").append(lineSep);
        }
```

**Comment by cyrille-leclerc** [comment]
thanks @marioja

**Pull request merged**
