### PR TITLE
[JENKINS-51675] Publish SpotBugs reports

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
[JENKINS-51675] Publish SpotBugs reports

### CODE REVIEW

**Comment by dantran** [comment]
This is off by default?

**Comment by cyrille-leclerc** [comment]
@dantran no, the SpotBugs publisher is on by default, similarly to the other publishers. It will search for invocations of the goal `com.github.spotbugs:spotbugs-maven-plugin.spotbugs` and silently skip if none is found.
I don't expect any performance impact caused by this new publisher.

Did you have something in mind?

**Comment by dantran** [comment]
Best to disable by default so that after upgrade lots of us dont have to manually disable it at global configuration  to remove any ambiguity and we have a number of Jenkins masters to go thru

**Comment by Syquel** [comment]
@cyrille-leclerc I agree with @dantran , because of the reasons mentioned by me in #149 .
The FindBugs Plugin is meant to be used with the Maven FindBugs Plugin and will not be maintained anymore. Therefore we will not see any official support for SpotBugs by this Jenkins Plugin and in the case of the divergence of the SpotBugs file format we will get issues if we execute the Jenkins FindBugs Plugin.

**Comment by cyrille-leclerc** [comment]
@Syquel 

>  I agree with @dantran 

Agree on what? On the idea to disable by default or on the idea to reuse the `FindbugsAnalysisPublisher` adding complexity to it to handle `spotbugs:spotbugs` instead of introducing a `SpotBugsAnalysisPublisher`.

> The FindBugs Plugin is meant to be used with the Maven FindBugs Plugin and will not be maintained anymore. 

The `SpotBugsAnalysisPublisher` could be very quickly be adapted to switch from the [Jenkins FindBugs Plugin](https://wiki.jenkins.io/display/JENKINS/FindBugs+Plugin) to a Jenkins SpotBugs if such plugin is being released


https://github.com/jenkinsci/pipeline-maven-plugin/pull/152/files#diff-a23a58b39dd48dd84d35e242a2c9ab43R230

**Comment by dantran** [comment]
@cyrille-leclerc  it is ok for the new spotbugs feature since we don't use spotbugs it is effectively disabled

**Comment by Syquel** [comment]
@cyrille-leclerc I only meant in regards to disabling it by default.
I agree with your argument that a seperate publisher makes sense in the case that a Jenkins SpotBugs plugin would be released. 
My only concern is that there will be no Jenkins SpotBugs plugin be released because the functionality will be included into the Warnings plugin as mentioned here: https://issues.jenkins-ci.org/browse/JENKINS-46975?focusedCommentId=327168&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-327168
And as soon as the SpotBugs XML format diverges from the old FindBugs data format I will have to disable the SpotBugs publisher everywhere.

**Comment by cyrille-leclerc** [comment]
@Syquel I would like to proceed with this dedicated SpotBugs Analysis Publisher and, when a solution more durable than the "Jenkins FindBugs Publisher" is available to collect SpotBugs reports (this solution is likely to be the jenkins warnings plugin), then we will change the underlying implementation and it will be transparent for the users of the withMaven plugin.

**Pull request merged**
