### PR TITLE
[JENKINS-49334] MavenLinkerPublisher option

### PR DESCRIPTION
**Pull request by bingshiao**
[JENKINS-49334](https://issues.jenkins-ci.org/browse/JENKINS-49334) MavenLinkerPublisher option

**MavenLinkerPublisher** is an optional publisher to **withMaven()** to publish links of deployed artifacts.

Unlike **GeneratedArtifactsPublisher**, **MavenLinkerPublisher** does not archive artifacts on master; simply track the deployed artifacts and display the url.

screen shot 2018-02-01 at 9 39 47 pm

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
Thanks @bingshiao, it's a very useful feature. 

I have to understand how you have succeeded in listening "org.eclipse.aether.RepositoryEvent", I think I had to exclude it due to classloader issues in Maven. Maybe caused by older versions of Maven.

**Comment by bguerin** [comment]
I think it depends of the maven version you run, no ? It should work with one but not with another

**Comment by cyrille-leclerc** [comment]
Successfully tested with both Maven 3.5.2 and 3.3.9 invokin `mvn clean deploy` on https://github.com/cyrille-leclerc/my-jar

**Comment by cyrille-leclerc** [comment]
❓ the file extension in the for the URL on the maven repository should probably be the mavenArtifact.extension rather than mavenArtifact.type . We need to check with a Jenkins HPI file.

https://github.com/jenkinsci/pipeline-maven-plugin/blob/1b28437a157d0d309833debdb3d56f358f7a5708/jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/MavenLinkerPublisher.java#L106

**Comment by bingshiao** [comment]
Yes, the handler is setting **type** attribute with mavenArtifact.extension. I guess it's better to change the attribute name to **extension**.

https://github.com/jenkinsci/pipeline-maven-plugin/blob/master/maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/ArtifactDeployedEventHandler.java#L73

**Pull request merged**
