### PR TITLE
feature: Supports maven-frontend-plugin when collecting unit test results [JENKINS-63689]

### PR DESCRIPTION
**Pull request by bguerin**
See https://issues.jenkins-ci.org/browse/JENKINS-63689

This one is a little bit ugly ... maven-karma-plugin does more than just launching karma, it pre-configures it to generate JUnit compatible XML reports in a given directory, thus exposed in the MOJO configuration.
Here maven-frontend-plugin is just a bypass, it installs node and karma locally and then just launch karma on the given configuration file, nothing more ... One has to configure karma himself to obtain JUnit compatible XML reports, but the plugin will not expose their parent path ... Using environmentVariables is the only trick I found to do that

### CODE REVIEW

**Comment by aheritier** [comment]
Thanks @bguerin 
Jira is working but you should use https://issues.jenkins-ci.org/browse/JENKINS-63689 instead of https://issues.jenkins.io/browse/JENKINS-63689

jenkins-ci.org vs jenkins.io

I warned the infra team about this issue.
The problem is known but still here : https://groups.google.com/g/jenkins-infra/c/cTqvrp5K_Ww

**Comment by bguerin** [comment]
Thanks a lot !! my bad ...

**Comment by aheritier** [comment]
it looks good to me. @bguerin now we have the doc in our repo could you also update the doc and potentially give a sample of usage ?

**Comment by bguerin** [comment]
Of course, will.

I will also add unit tests for other plugins once this PR is merged

**Review by aheritier — APPROVED** [review]
LGTM Thx a lot @bguerin

**Pull request merged**
