### PR TITLE
just to avoid downloading maven distro every time you run mvn clean verify

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Review by aheritier — APPROVED** [review]
Good improvement.
Not sure if changing the maven version used for tests in the same PR was required and the impact it has in term of compatibility (even if myself ... I have no idea why some users are stuck on very old maven versions)

**Comment by bguerin** [comment]
Thanks @olamy 

But I agree with @aheritier , I do not want to change maven version for now. My plan is to "cure" the plugin technically first (testcontainers, junit5, ...), then add more tests to ensure compatibility (Java 6, Java 8, Java 11, ... and according maven versions), and then we could use latest versions for building, as long as tests remains OK

But please, keep your PR open, I will work on it.

> I have no idea why some users are stuck on very old maven versions

Because of Java 6 / 8 compatibility, on legacy code

**Comment by olamy** [comment]
> Thanks @olamy
> 
> But I agree with @aheritier , I do not want to change maven version for now. My plan is to "cure" the plugin technically first (testcontainers, junit5, ...), then add more tests to ensure compatibility (Java 6, Java 8, Java 11, ... and according maven versions), and then we could use latest versions for building, as long as tests remains OK
> 
> But please, keep your PR open, I will work on it.
> 
> > I have no idea why some users are stuck on very old maven versions
> 
> Because of Java 6 / 8 compatibility, on legacy code

Frankly better to test with last Maven GA.
Bear in mind 3.6.3 is not supported anymore.
See supported core versions https://maven.apache.org/docs/history.html

**Comment by bguerin** [comment]
> Frankly better to test with last Maven GA and forget about jdk 6 which is not supported anymore

I agree, I want to test against all supported branches

Regarding JDK6/8, by the time I manage to end with my plan, maybe it will not be a question anymore, but right now, I just cannot drop it like that

https://github.com/jenkinsci/pipeline-maven-plugin/pull/587#issuecomment-1418260847

There is what we, as maintainers, would like to do, and old versions we would like to drop ... and what we can really do, for our users

**Comment by olamy** [comment]
> > Frankly better to test with last Maven GA and forget about jdk 6 which is not supported anymore
> 
> I agree, I want to test against all supported branches
> 
> Regarding JDK6/8, by the time I manage to end with my plan, maybe it will not be a question anymore, but right now, I just cannot drop it like that
> 
> [#587 (comment)](https://github.com/jenkinsci/pipeline-maven-plugin/pull/587#issuecomment-1418260847)
> 
> There is what we, as maintainers, would like to do, and old versions we would like to drop ... and what we can really do, for our users

Frankly I don't get jdk6?? 
this is definitely not supported anymore....

**Comment by olamy** [comment]
FYI https://endoflife.date/java (jdk6 still sure of that? :) )

**Comment by bguerin** [comment]
> > > Frankly better to test with last Maven GA and forget about jdk 6 which is not supported anymore
> > 
> > 
> > I agree, I want to test against all supported branches
> > Regarding JDK6/8, by the time I manage to end with my plan, maybe it will not be a question anymore, but right now, I just cannot drop it like that
> > [#587 (comment)](https://github.com/jenkinsci/pipeline-maven-plugin/pull/587#issuecomment-1418260847)
> > There is what we, as maintainers, would like to do, and old versions we would like to drop ... and what we can really do, for our users
> 
> Frankly I don't get jdk6?? this is definitely not supported anymore.... You can't even test it with CI (jenkins oss ci is not supporting that) GH action?? it sounds a bit awkward to test a Jenkins plugin with gh action... rofl

With docker, you can do everything ;)

How I can be sure that I would not break users by dropping Java 6 support ? Even if, I agree, it is very very old, and very very unsupported ...
Right now, I would test:
- Java 6 / Maven 3.2
- Java 8 / Maven 3.9 (cool Maven has not switched to Java 11 anymore, I thought it was the case)
- Java 11 / latest Maven (so 3.9 right now, waiting for 4)

**Comment by olamy** [comment]
Again what is the point of jdk 6 and maven 3.6 in 2023
They are both totally abandoned!! 
You cannot even find commercial support for those versions!
It's totally waste of time...

**Comment by bguerin** [comment]
Ok for Java 6
I am just not fan of dropping support just because it is old and not supported anymore, if technically it is still working and not a problem to make it work (which is the case in this plugin, the only thing really tied to Java / Maven is the spy, which is compiled to Java 6 bytecode)
BUT, I will do this in another PR

FYI, I am fixing other places where Maven version is hardcoded

**Comment by olamy** [comment]
> Ok for Java 6 I am just not fan of dropping support just because it is old and not supported anymore, if technically it is still working and not a problem to make it work (which is the case in this plugin, the only thing really tied to Java / Maven is the spy, which is compiled to Java 6 bytecode) BUT, I will do this in another PR
> 

yes and no ...
you just can't use new java features ;) 

> FYI, I am fixing other places where Maven version is hardcoded

**Comment by olamy** [comment]
I have updated the PR with rerverting back to 3.6.3

**Comment by bguerin** [comment]
> I have updated the PR with rerverting back to 3.6.3

:sob: 

> the version is really too much hardcoded atm

agree

> you just can't use new java features ;)

I know. But again, there is the plugin AND the spy ...
When I talk about keeping compatibility, I am talking about the spy only, which is basic code to write an XML based on Maven events. This spy is the only part running IN the user JVM running the maven build itself. Rest of the code is the plugin it self, which is running in Jenkins agent, thus constrained to Jenkins runtime compatibility.
For the plugin itself, I do want to keep in sync with Jenkins core, so I should already have switch to Java 11, dropping Java 8, I am just missing time

**Comment by olamy** [comment]
> > I have updated the PR with rerverting back to 3.6.3
> 
> sob

no worries I will restore that.

> 
> > the version is really too much hardcoded atm
> 
> agree
> 
> > you just can't use new java features ;)
> 
> I know. But again, there is the plugin AND the spy ... When I talk about keeping compatibility, I am talking about the spy only, which is basic code to write an XML based on Maven events. This spy is the only part running IN the user JVM running the maven build itself. Rest of the code is the plugin it self, which is running in Jenkins agent, thus constrained to Jenkins runtime compatibility. For the plugin itself, I do want to keep in sync with Jenkins core, so I should already have switch to Java 11, dropping Java 8, I am just missing time

Sure I know how this work and this is not my point :)
but look with using such compiler configuration, you're not really ensuring this will work with jdk6 when compiling with jdk6.
```
          <source>1.6</source>
          <target>1.6</target>
```

using `<release>6</release>` is not anymore supported with jdk17.
Again my point is jdk6 is totally dead, jdk8 sounds a good minimum even if I would prefer jdk11 but that's fine.
No problem you will have people to help ;)

**Comment by bguerin** [comment]
> using <release>6</release> is not anymore supported with jdk17

Ok, I was ignoring that ...

**Comment by olamy** [comment]
> > using 6 is not anymore supported with jdk17
> 
> Ok, I was ignoring that ...

btw the current build need jdk 11 as `com.github.ekryd.sortpom:sortpom-maven-plugin:3.2.1` is jdk11 minimum ;)

**Comment by bguerin** [comment]
Reintegrated in #705

**Pull request closed without merging**
