### PR TITLE
Do not override maven-invoker-plugin results [JENKINS-64732]

### PR DESCRIPTION
**Pull request by bguerin**

### CODE REVIEW

**Review by aheritier — COMMENTED** [review]
it looks so simple that I don't get it :-)
I will have to review the code

**Comment by bguerin** [comment]
I cannot explain in details myself ...
I saw this fix some time ago in the JUnitPublisher
I have 2 projects, one single module with 13 invoker tests and another multimodule with 6 tests
Before this fix, I saw only one test for each. With this fix I can see all the tests, on each project

**Comment by aheritier** [comment]
@bguerin on the 2nd module these are also invoker tests or classical tests ?

**Comment by bguerin** [comment]
both

**Review by aheritier — APPROVED** [review]

**Pull request merged**
