### PR TITLE
fix JENKINS-62358: NonProductionGradeDatabaseWarningAdministrativeMonitor slowing down startup

### PR DESCRIPTION
**Pull request by bguerin**
fix https://issues.jenkins.io/browse/JENKINS-62358

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by aheritier — COMMENTED** [review]
@bguerin I think this fix is ok but maybe not enough.
As shared @jglick here you are avoiding to do the test if it's not configured but for real users it won't help and I am not sure if there is something we can do.
Do we know if the query used here is optimized (with an index?)

**Comment by bguerin** [comment]
You're right, I will check queries used
But the main problem is to find the difference between an unconfigured because unused installation, and an unconfigured but used one. I fear the fix currently consider both the same and hide the monitor in both case, which is not what we want for the second case

**Review by jglick — APPROVED** [review]
Should help by making the short-circuit check much lighter-weight. I think you could even just discard `NonProductionGradeDatabaseWarningAdministrativeMonitor` and make this a matter of documentation, or print a message to the build log, etc.

**Comment by bguerin** [comment]
@aheritier I checked the queries, no more we can do

@jglick I think this is already documented, in [our wiki](https://github.com/jenkinsci/pipeline-maven-plugin#database-setup), and in [the help of the configuration page](https://github.com/jenkinsci/pipeline-maven-plugin/blob/master/jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig/help-jdbcUrl.html#L4). I am changing the way we show the warning to avoid at best to init the DAO (and load classes ...). I understand this monitor is noisy for people not using our plugin, and I think this is now fixed. But for people using it, I want this monitor to show, help is something but it can discarded, not read, etc ... I can also imagine organizations where installing / configuring Jenkins infrastructure is done by administrators, and builds are ran / watched by other people, so I prefer to avoid using build log too.

**Comment by jglick** [comment]
Really it should be using the `database` plugin, and if no DB is configured, just do not record snapshot info.

**Comment by bguerin** [comment]
@jglick make sense, but is a big change. If @aheritier agrees, I think I will merge this as it, and migrate to `database` plugin in another PR

**Review by aheritier — APPROVED** [review]
sure let's go.
Thanks @bguerin and @jglick

**Comment by jonesbusy** [comment]
Found this thread while looking up for info related to database plugin and pipeline-maven-plugin

I would love to do something like this on JcasC (instead of duplicating configuration, adding a credentials etc...). 

```
  pipelineMaven:
    storage: "database"
```

Like is done on the junit plugin

```
  junitTestResultStorage:
    storage: "database"
```

I'm not sure if easier to implement after the recent split of pipeline-maven-plugin.

Regards,

**Comment by bguerin** [comment]
Hello @jonesbusy 
the recent split is the first step to this path. Clearly the goal is to remove all JDBC stuff and use the `database` plugin for that

**Pull request merged**
