### PR TITLE
JENKINS-46368 : Record parent of the main project as a dependency

### PR DESCRIPTION
**Pull request by bguerin**
To allow the dependency trigger mechanism to work if the parent POM change

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
Thanks @bguerin, the more I think of this, the more I feel that the parent pom should not be treated as a dependency but that we should introduce a dedicated entity in the data model. 

@bguerin What do you think? You chose to declare the parent pom as a dependency of type "pom", correct? The type "pom" exists with the scope "import" for Maven "BOM" (1). Isn't there a collision here?

Note that I feel we have to verify how a "bom" behaves.

(1) http://blog.xebia.fr/2014/02/28/la-notion-de-bom-avec-maven/

**Comment by bguerin** [comment]
I understand your concerns. I will test a sample project with a BOM to see how your plugin react on it

However, handling BOMs is, for me, another feature. It has just been added on Maven Project Type ([JENKINS-15883](https://issues.jenkins-ci.org/browse/JENKINS-15883)). Maybe we can keep going as it for now, and change when adding BOM support

**Comment by bguerin** [comment]
@cyrille-leclerc I have tested a sample project with spring-boot BOM. It does not appear anywhere in the spy log, because BOM are in the _dependencyManagement_ section, not the _dependency_ one.
Maybe in a near future another PR will add support for BOMs :)

For now, do you want me to add an explicite model for parent POM ?

**Comment by cyrille-leclerc** [comment]
@bguerin FYI I have initiated https://github.com/jenkinsci/pipeline-maven-plugin/pull/104/ with a dedicated database table `MAVEN_PARENT_PROJECT`

**Comment by cyrille-leclerc** [comment]
@bguerin sorry for the late answer. I have been busy with the incompatibility of docker-pipeline:1.14 with withMaven.

> Do you want me to test ?

It would be great. I still want to add a test case.

> So, should close this pr no ?

Please no. @markusdlugi said in a comment on [JENKINS-46368#comment-320843](https://issues.jenkins-ci.org/browse/JENKINS-46368?focusedCommentId=320843&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-320843) that he prefers your approach. The debate is opened.

**Comment by bguerin** [comment]
> sorry for the late answer. I have been busy with the incompatibility of docker-pipeline:1.14 with withMaven.

No problem at all :)

> It would be great

This is already the case actually. I have built a custom version of your plugin, with this PR in it, and it is running in our production CI.

It is working well (registering and triggering builds)

I just had something weird : after the restart of our Jenkins because of the update of the plugin, I got an exception saying that table _MAVEN_PARENT_PROJECT_ does not exists (loading of the DAO occured because of a build).
And when I went to the tools configuration page, it said _null_ for the DAO
So I restarted Jenkins, went to the tools configuration page, and this time, upgrade of the H2 database was done and everything went fine

**Pull request closed without merging**
