### PR TITLE
[JENKINS-19508] Eliminate some optional deps

### PR DESCRIPTION
**Pull request by jglick**
As per [JENKINS-19508](https://issues.jenkins-ci.org/browse/JENKINS-19508), you should avoid `optional` dependencies unless you really know what you are doing, and even then you should avoid them, and if you really need to use them you must take care to test the plugin with the dependencies missing.

In this case if `branch-api` is not present but `pipeline-maven-plugin` is, Jenkins explodes when trying to create a new project (not even Pipeline!):

```
java.lang.NoClassDefFoundError: jenkins/branch/MultiBranchProject
	at org.jenkinsci.plugins.pipeline.maven.trigger.WorkflowJobDependencyTrigger$DescriptorImpl.isApplicable(WorkflowJobDependencyTrigger.java:30)
```

crashes the job configuration screen.

@reviewbybees

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
👍  thanks @jglick

**Comment by jglick** [comment]
Timeout due to some crazy Maven behavior looking for snapshots of Stapler:

```
…
00:25:16.254 [linux-8] [INFO] --- maven-enforcer-plugin:1.4.1:enforce (display-info) @ pipeline-maven ---
00:25:17.723 [linux-8] [INFO] artifact org.kohsuke.stapler:stapler: checking for updates from azure
00:25:19.222 [linux-8] [INFO] artifact org.kohsuke.stapler:stapler: checking for updates from central
00:40:56.927 [linux-8] Aug 24, 2017 6:22:55 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
00:40:56.927 [linux-8] INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection timed out (Read failed)
00:40:56.927 [linux-8] Aug 24, 2017 6:22:55 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
00:40:56.927 [linux-8] INFO: Retrying request to {s}->https://repo.maven.apache.org:443
00:56:34.656 [linux-8] Aug 24, 2017 6:38:31 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
00:56:34.657 [linux-8] INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection timed out (Read failed)
00:56:34.657 [linux-8] Aug 24, 2017 6:38:31 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
00:56:34.657 [linux-8] INFO: Retrying request to {s}->https://repo.maven.apache.org:443
00:56:34.657 [linux-8] [INFO] Downloading: https://repo.azure.jenkins.io/public/org/jenkins-ci/plugins/junit/1.3/junit-1.3.jar
…
```

**Comment by jglick** [comment]
@reviewbybees done

**Comment by jglick** [comment]
Filed [INFRA-1310](https://issues.jenkins-ci.org/browse/INFRA-1310) to track the build issue.

**Pull request merged**
