### PR TITLE
[JENKINS-51675] Add support for SpotBugs to FindbugsAnalysisPublisher.

### PR DESCRIPTION
**Pull request by Syquel**
Introducing support for SpotBugs into the FindbugsAnalysisPublisher, because Findbugs has been deprecated and its fork "SpotBugs" will be its successor.

I opted for the introduction of a flag into the FindbugsAnalysisPublisher instead of creating a new publisher because

1. there were only minimal changes to be made.
2. the Jenkins FindBugs Plugin is or will most probably be deprecated in favor of the Jenkins Warnings Plugin before SpotBugs introduces significant changes to it's XML format. [(JENKINS-46975)](https://issues.jenkins-ci.org/browse/JENKINS-46975?focusedCommentId=327168&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-327168)

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
@Syquel did you consider the plugin to search for both executions of findbugs and spotbugs instead of asking the pipeline author to specify what to look for?
The philosophy of this plugin is to minimise the configuration effort as the plugin is expected to have a deep knowledge of Maven and of Jenkins.

It's what we do with the JunitTestsPublisher looking for both executions of the maven-surefire-plugin and maven-failsafe-plugin.

https://github.com/jenkinsci/pipeline-maven-plugin/blob/pipeline-maven-3.5.5/jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher.java

**Comment by Syquel** [comment]
@cyrille-leclerc there were multiple reasons for me to implement it this way.

1. I did not want to change the default behavior of the Pipeline Maven Plugin to make it easier to introduce support for SpotBugs without breaking anything.
2. I do not know how the Jenkins FingBugs Plugin behaves in case of multiple executions (i.e. one findbugs and one spotbugs xml), which might result in duplication of reported issues or other issues.
I would therefore enforce that by default only one file gets processed.
3. I wanted to avoid issues in case the SpotBugs XML format diverges from the FindBugs XML format by defining the processing of  the FindBugs XML as the default behavior (i.e. without the "pluginType" parameter set)

In the end it's your call and I will adjust the code according to your requirements.

**Comment by cyrille-leclerc** [comment]
Sorry for the delay, I prefer to create a dedicated publisher. I'm initiating a branch today for this, I have few hours in a train.

**Comment by cyrille-leclerc** [comment]
See https://github.com/jenkinsci/pipeline-maven-plugin/pull/152

**Comment by cyrille-leclerc** [comment]
@Syquel could you please test https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/pipeline-maven/3.5.8-beta-1/pipeline-maven-3.5.8-beta-1.hpi ?

**Comment by cyrille-leclerc** [comment]
Problem solved differently: https://github.com/jenkinsci/pipeline-maven-plugin/pull/152

**Pull request closed without merging**
