### PR TITLE
[JENKINS-43650] Add dependency to org.jenkins-ci.main:maven-plugin.

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
[JENKINS-43650](https://issues.jenkins-ci.org/browse/JENKINS-43650) Add dependency to org.jenkins-ci.main:maven-plugin.

Will also be needed to manage global-level and folder-level settings.

### CODE REVIEW

**Comment by jtnord** [comment]
@cyrille-leclerc I think you can revert this - I was having a bad day at the office when I reported it :-(

**Comment by cyrille-leclerc** [comment]
@jtnord we will need it to get configuration parameters from the global settings.

**Comment by jtnord** [comment]
@cyrille-leclerc which configuration parameters?  You can use `withMaven()`  with just a maven installation and no configuration (if said config is in your build environment - aka not managed by Jenkins)...

Config-File-Provider also has entries for maven stuff without the maven-plugin

**Comment by cyrille-leclerc** [comment]
@jtnord I am thinking of 
* Global MAVEN_OPTS
* Local Maven Repository: "Default (~/.m2/repository)", "Local to the executor", "Local to the workspace"

We also want settings to globally disable things like "automatic archiving", "automatic fingerprinting of dependencies", ...

**Comment by jtnord** [comment]
@cyrille-leclerc my concern is that if we depend on that plugin then the maven plugin sticks around for a long long time (and the maven job type becomes self-discoverable as soon as you install maven-pipeline-plugin).

I think these may be best served in a different configuration area, and even then I'm not convinced that this belongs in global config (rather than a global pipeline library) - and really just parameters to `withMaven()`

**Comment by alvarolobato** [comment]
Another option is to discover if the plugin is installed and provide the functionality in that case, avoiding the dependency or at least making it optional.

**Comment by batmat** [comment]
/me dies a little more inside :-). If we keep adding dependencies to that plugin, it will indeed stick forever :-(

**Pull request merged**
