### PR TITLE
feature: Conceal console lines from Maven downloads [JENKINS-51182]

### PR DESCRIPTION
**Pull request by bguerin**
See https://issues.jenkins.io/browse/JENKINS-51182

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by IppX** [comment]
Hi, just FYI this change means that the user now needs maven 3.6.1+, as this option `--no-transfer-progress` has only been introduced in [that version](https://maven.apache.org/docs/3.6.1/release-notes.html#user-visible-changes). Any usage of earlier versions of maven will fail.

**Comment by advorsky73** [comment]
Thanks for breaking the backward compatibility without announcing it and making us search for the issue like idiots....
Can this be reverted?? We need to make builds with old maven installations 3.5.x for compatibility reasons to our released versions...

**Comment by bguerin** [comment]
@advorsky73 well ... Maven < 3.8 is EOL for a while
https://maven.apache.org/docs/history.html

and I do not see any reason why a build running with Maven < 3.8 could not run with Maven 3.8, so yes, requiring at least Maven 3.6.3 seems not a big deal for me.

It is now noted in the release notes, but no, it will not be reverted. I can't keep compatibility with EOL stuff

**Comment by Brialius** [comment]
> It is now noted in the release notes, but no, it will not be reverted. I can't keep compatibility with EOL stuff

Yet another plugin to freeze.. because of the implicit flag, which can be added by user, but can't be removed. Does it worth this breaking change? ¯\_(ツ)_/¯

**Pull request merged**
