### PR TITLE
WIP [JENKINS-44721] Trigger pipelines that depend on generated snapshot artifacts

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
[JENKINS-44721](https://issues.jenkins-ci.org/browse/JENKINS-44721) Trigger pipelines that depend on generated snapshot artifacts

# TODO

* [ ] better handling of database error: add a circuit breaker
* [x] verify the security logic in [org.jenkinsci.plugins.pipeline.maven.listeners.DownstreamPipelineTriggerRunListener#onCompleted](https://github.com/jenkinsci/pipeline-maven-plugin/blob/0291bb0f74e7c1332a33c7e8990363edb18de056/jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java). There are cases, at least with CloudBees RBAC authorization, were the downstream job is not triggered for security reasons that seem to be invalid (see [here](https://github.com/jenkinsci/pipeline-maven-plugin/blob/0291bb0f74e7c1332a33c7e8990363edb18de056/jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java#L97))
* [ ] support an external H2 database instead of the inprocess h2 (may be done in a subsequent version)
* [ ] support PostgreSQL (will be done in a subsequent version)

# Testing the downstream trigger

## Testing dataset

* Upstream job: simple pipeline job `my-jar` using the script 
```
node {
    stage ("Build") {
        git "https://github.com/cyrille-leclerc/my-jar.git"
        withMaven(maven:"maven-3.5.0") {
            sh "mvn clean install"
        }
    }
}
```

* Downstream job: multibranch pipeline job `my-war` for https://github.com/cyrille-leclerc/my-war

## Testing steps

* Launch Jenkins, maybe `mvn hpi:run` from your IDE to use a debugger
* Enable logs on the pipeline-maven-plugin
* Launch `my-jar`
   * The generated jar gets registered in the database of maven artifacts
* Launch `my-war`
   * The jar `my-jar` gets registered as a dependency of `my-war.war`
* Launch `my-jar`, the build should trigger a downstream build of `my-war/master` and the build logs of `my-jar` should display, at the end of the logs 
```
[withMaven] Scheduling downstream pipeline my-war » master...
```

### CODE REVIEW

**Comment by bguerin** [comment]
Currently testing.
Reading the PR, I found typos on test ressources names :
jenkins-plugin/src/test/resources/h2/**pipleine**-maven-plugin...

**Comment by cyrille-leclerc** [comment]
Thanks @bguerin, good catch but I don't think it's a big issue as tthese db file were stored to help understand the data in the db, they are not used in unit tests.

**Comment by cyrille-leclerc** [comment]
@bguerin FYI I have added a TODO section to this PR

**Comment by bguerin** [comment]
> I don't think it's a big issue as tthese db file were stored to help understand the data in the db, they are not used in unit tests 
agreed, was just for your information

> I have added a TODO
nice

From my tests (but I haven't finished yet) :
- the internal H2 database is well created
- detection of artefacts and filling of the database is OK
- "cleaning" of the database (build deletion, job renaming, job deletion) is OK

I did not managed to get a downstream job launched because, for now, my downstream job fails to build. The dependencies are thus not seen by the spy, so not recorded.
The only workaround I see for this would be to detect and record dependencies at the begining of the step, before launching the real maven command. But it would mean playing with Maven dependency requester (ex Aether) ...

**Comment by cyrille-leclerc** [comment]
> I did not managed to get a downstream job launched because, for now, my downstream job fails to build. 
> The dependencies are thus not seen by the spy, so not recorded.

Can you attach a gist of the build logs? I don't understand which dependency is not found, the pom.xml of my-war is declaring a repository for
 my-jar:0.2-SNAPSHOT. 

 my-jar:0.2-SNAPSHOT should be donwloaded from https://nexus.beescloud.com/content/repositories/snapshots/com/example/my-jar/0.2-SNAPSHOT/

**Comment by bguerin** [comment]
I test with internal projects of my company :)

**Comment by cyrille-leclerc** [comment]
understood, could ```mvn install:install-file -Dfile=<path-to-file> -DgroupId=<group-id> -DartifactId=<artifact-id> -Dversion=<version> -Dpackaging=<packaging>``` help to prepare the environment?

https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html

**Comment by bguerin** [comment]
Tests done, it works !

But it is a pitty that parameterized jobs are not triggered, whereas in historical jobs (configured through Jenkins GUI), downstream parameterized jobs are triggered with default parameters.

**Comment by cyrille-leclerc** [comment]
> Tests done, it works !

Can you please describe the authorization configuration? 

* Which authorization strategy?
* Parent job launched manually or launched by a trigger

> But it is a pitty that parameterized jobs are not triggered, whereas in historical jobs (configured through Jenkins GUI), downstream parameterized jobs are triggered with default parameters.

Subject to improvement ;-)

The code is here: https://github.com/jenkinsci/pipeline-maven-plugin/blob/0291bb0f74e7c1332a33c7e8990363edb18de056/jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java#L75

**Comment by bguerin** [comment]
No authorization strategy.
Parent launched manually.

Of course, will look at the code :)

**Comment by bguerin** [comment]
- Fixed disabled and parameterized downstream jobs
- Tested with Cron Trigger : OK

**Pull request merged**
