### PR TITLE
Allow to silent traceability information

### PR DESCRIPTION
**Pull request by tkalmar**
Adds a verbose parameter to the step execution, defaults to true, so the initial behaviour is not changed.
Can turn of the version info and the `----- withMaven Wrapper script -----` line

 Fixes https://issues.jenkins.io/browse/JENKINS-58425

### CODE REVIEW

**Comment by aheritier** [comment]
Hi @tkalmar 

Thanks a lot for this contribution and sorry for the too long delay to come back to you.
I am completely supporting the addition of such option but I would have liked to call the option `traceability` instead of `verbose`as described in the documention : https://github.com/jenkinsci/pipeline-maven-plugin#feature-traceability
It's a feature but I agree that we should be able to disable it. Thus it my be great to have the option called `traceability`, keeping it to true by default and users could disable it
(maybe we can also allow to disable it globally in the future)

**Comment by tkalmar** [comment]
@aheritier Thanks for your feedback, i renamed all references.

**Review by aheritier — COMMENTED** [review]
@tkalmar thanks a lot it's very good like this.

It's outside of the scope of https://issues.jenkins.io/browse/JENKINS-58425 which is really targeting the extra info in the script output but do you think we should try also to hide the lines like 

`console.println("[withMaven] using...`

Which are producing these traceability lines

```
[withMaven] Options: []
[withMaven] Available options: 
[withMaven] using JDK installation provided by the build agent
[withMaven] using Maven installation provided by the build agent with the environment variable MAVEN_HOME=/usr/share/maven
```

I am not sure myself cc @bguerin

**Comment by tkalmar** [comment]
I can filter out the four mentioned lines, but there are a lot more (26 Messages prefixe with `[withMaven]`.
If all this messages should be filtered out i can do this whithin this PR if the messages are not all of the same importance i would suggest to tackle this in an extra PR (probably by someone who knows more about which messages are important and which are not)

**Comment by aheritier** [comment]
@tkalmar yes we can do it in another PR
it's probably better, it was just to get your feeling about it.

**Comment by bguerin** [comment]
@aheritier
like @tkalmar I call withMaven for some one time things where I do not want a polluted output because I will use maven result output. So I love this `traceability` approch, it will simplify my scripts
But we are here talking out the output of Maven itself, the `[withMaven]` are not part of this output, they are in the build log. For me they are not problematic, but maybe we can also add an option (same or other, I don't know) to turn these messages off

**Comment by aheritier** [comment]
I agree @bguerin 

I think (maybe @cyrille-leclerc can confirm) that the lines generated by the wrapper script + the `--show-version` of maven

```
----- withMaven Wrapper script -----
 Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T19:49:05Z)
 Maven home: /var/lib/jenkins/tools/hudson.tasks.Maven_MavenInstallation/mvn-3.5.3
 Java version: 1.8.0_161, vendor: Oracle Corporation
 Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre
 Default locale: en_US, platform encoding: UTF-8
 OS name: "linux", version: "3.10.0-693.17.1.el7.x86_64", arch: "amd64", family: "unix"
```

are serving the same purpose of `traceability` than the line in the console

```
[withMaven] Options: []
[withMaven] Available options: 
[withMaven] using JDK installation provided by the build agent
[withMaven] using Maven installation provided by the build agent with the environment variable MAVEN_HOME=/usr/share/maven
```

I completely understand how the wrapper ones are annoying for some usecases but I suppose that we should hide in the future the console logs too if we consider that all of them are part of this `traceability` feature

**Comment by bguerin** [comment]
agree too ;)

**Comment by tkalmar** [comment]
I added a commit, which tries to check console messages if the should be traced or not. This often overlaps with the Logger and `LogLevel.FINE` perhaps should all this trace informations be written to the LOGGER in the first place? One could get rid of the `[withMaven]` prefix and there would be one sinlge source of information and configuration for it. The traceability feature should then only concern the areas of the initial bug (now wrapped in `ifTraceabilityEnabled` method

**Comment by aheritier** [comment]
thanks a lot @tkalmar for your efforts here. I agree that the code could be improved to avoid the mixup with Logging levels.
It's something which can be done in another PR. Here you implemented JENKINS-58425 which is already a very useful improvement. thx

**Pull request merged**
