### PR TITLE
update Jenkins baseline to 2.303.x

### PR DESCRIPTION
**Pull request by bguerin**
Jenkins LTS switched from 2.303.x to 2.319.x, so upgrade our baseline too.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [n/a] Link to relevant issues in GitHub or Jira
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by bguerin** [comment]
@aheritier 2.303 is now LTS N-2, do you agree to switch to it ?

**Comment by aheritier** [comment]
Yes fine for me @bguerin I think what is important is to have a new release out as soon as possible

**Comment by bguerin** [comment]
> I think what is important is to have a new release out as soon as possible

I know and agree. As asked on JIRA, do you have some time in the coming days to teach me how to cut a release ?

**Comment by aheritier** [comment]
Yes with pleasure. Just send me an email and we book a slot for it

**Pull request merged**
