### PR TITLE
chore: Add unit test for JUnitPublisher

### PR DESCRIPTION
**Pull request by bguerin**

### CODE REVIEW

**Comment by aheritier** [comment]
Thanks a lot @bguerin I will review it later this week. I love when we add some tests !!!

The build failure isn't from your PR AFAICS

https://github.com/jenkinsci/pipeline-maven-plugin/tree/master/jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_nbm_base_project

we are doing some tests with netbeans des and the repo manager isn't available anymore

for now I don't find where it could have been move, I have to dig more (maybe @jglick knows ...)

```
22:02:52  [ERROR] Failed to execute goal on project maven_nbm_dependency_project: Could not resolve dependencies for project com.netbeans.sample:maven_nbm_dependency_project:nbm:0.0.1-SNAPSHOT: Failed to collect dependencies at org.netbeans.api:org-netbeans-api-annotations-common:jar:RELEASE82: Failed to read artifact descriptor for org.netbeans.api:org-netbeans-api-annotations-common:jar:RELEASE82: Could not transfer artifact org.netbeans.api:org-netbeans-api-annotations-common:pom:RELEASE82 from/to netbeans (https://bits.netbeans.org/nexus/content/groups/netbeans): Transfer failed for https://bits.netbeans.org/nexus/content/groups/netbeans/org/netbeans/api/org-netbeans-api-annotations-common/RELEASE82/org-netbeans-api-annotations-common-RELEASE82.pom 502 Bad Gateway -> [Help 1]
```

**Comment by jglick** [comment]
@aheritier that repository is dead. `RELEASE121` ought to be on Central.

**Comment by proxxz** [comment]
We should wait to merge this until #302 is merged.

**Comment by proxxz** [comment]
@aheritier I'm not sure the surefire-reports and failsafe-reports files should be committed.

**Comment by bguerin** [comment]
> @aheritier I'm not sure the surefire-reports and failsafe-reports files should be committed.

why ? these files are needed for the tests to pass, because `JUnitResultArchiver` (static call from the publisher) parse them to produce the `TestResultAction`

**Comment by proxxz** [comment]
@bguerin, Thanks for the clarification.

**Review by proxxz — APPROVED** [review]

**Review by aheritier — APPROVED** [review]
tested on my side after a rebase it's ok

**Pull request merged**
