### PR TITLE
JENKINS-45265 : Add support for the maven-invoker-plugin

### PR DESCRIPTION
**Pull request by bguerin**
https://issues.jenkins-ci.org/browse/JENKINS-45265

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
Thanks @bguerin, it's a great idea. I'm moving to a new flat this weekend, I'm super busy. I'll review next week.

**Comment by bguerin** [comment]
@cyrille-leclerc any update on this ?

**Comment by cyrille-leclerc** [comment]
@bguerin can this be merged without merging #64 ?

**Comment by bguerin** [comment]
@cyrille-leclerc yes this and #64 are not linked

**Comment by bguerin** [comment]
Yeah ! thanks !

**Pull request merged**
