### PR TITLE
JENKINS-46029 : WorkflowJobDependencyTrigger should be associated wit…

### PR DESCRIPTION
**Pull request by bguerin**
…h a @symbol

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
@bguerin you act faster than I have the time to think :-)

I was considering to pick a more meaningful name.

I found:
hudson.triggers.SCMTrigger -> pollSCM
hudson.triggers.TimerTrigger -> cron
jenkins.triggers.ReverseBuildTrigger -> upstream

Maybe we could use `snapshotDependencies`

```
properties( pipelineTriggers([snapshotDependencies()]) ) // proposal
```

@bguerin what do you think of this?

**Comment by bguerin** [comment]
:+1:

**Comment by bguerin** [comment]
PR updated

**Comment by cyrille-leclerc** [comment]
Thanks @bguerin, I'll try to write a unit test

**Comment by bguerin** [comment]
@cyrille-leclerc done :) See #76

**Pull request merged**
