### PR TITLE
JENKINS-57543 Fix PostgreSQL database initialisation bugs.

### PR DESCRIPTION
**Pull request by cyrille-leclerc**

### CODE REVIEW

**Comment by jansohn** [comment]
I'm still seeing these errors/warnings with 3.7.1:

```
db_1       | 2019-06-05 14:12:57.254 UTC [71] ERROR:  relation "version" does not exist at character 15
db_1       | 2019-06-05 14:12:57.254 UTC [71] STATEMENT:  SELECT * FROM VERSION
db_1       | 2019-06-05 14:22:15.517 UTC [71] ERROR:  function aurora_version() does not exist at character 8
db_1       | 2019-06-05 14:22:15.517 UTC [71] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
db_1       | 2019-06-05 14:22:15.517 UTC [71] STATEMENT:  select AURORA_VERSION()
```

**Comment by cyrille-leclerc** [comment]
@jansohn where do you see this message? in the logs of the database or in Jenkins logs?

We invoke this function to test if the PostgreSQL instance is an Amazon Aurora instance but we catch the exception if this function does not exist (which means that it is not an Amazon Aurora database).
Would we have a bug catching the exception? 

https://github.com/jenkinsci/pipeline-maven-plugin/blob/pipeline-maven-3.7.1/jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginPostgreSqlDao.java#L69

**Comment by jansohn** [comment]
Logs of the database, so I guess if there is no other way than calling a function to test if it is available then we cannot get rid of it.

**Comment by cyrille-leclerc** [comment]
@jansohn yes, the only way I found to know if the PostgreSQL (or a MySQL database) is an Amazon Aurora database is to try to invoke the function `SELECT AURORA_VERSION();`.

See https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Updates.html

Is this error message an issue for you?
Identifying clearly the version number is very important for us for troubleshooting and support.

I am curious, can you share with us your feedback on using PostgreSQL with the Pipeline Maven Plugin? Can you share with us the numbers of rows in the database? Can you shared the report in "Manage Jenkins / Global Tools Configuration"?

**Comment by jansohn** [comment]
No, it doesn't seem to be an issue, it's just cosmetic. I've only just installed it on our new Jenkins instance so it's pretty much completely empty.

**Comment by cyrille-leclerc** [comment]
Thanks for the feedback @jansohn .
If you find a solution to check aurora without generating a warning message in the logs of the database, please don't hesitate to share this with us or, even better, don't hesitate to submit a pull request.

**Pull request merged**
