### PR TITLE
bugfix: properly apply schema migrations to PostgreSQL databases

### PR DESCRIPTION
**Pull request by kevinhuber**
The db migration scripts for PostgreSQL insert additional rows into the `VERSIONS` table which (after an initial setup) prevents any further migrations as old migrations keep getting applied over and over.
The SQL scripts for MYSQL and H2 properly overwrite the existing row in the `VERSIONS` table (they are not affected by this bug).

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by aheritier** [comment]
I prefer to let @bguerin review this one as I don't use Postgres. If required he can do a bug fix release.

**Comment by bguerin** [comment]
Hello,

Thank you for your pull request.

I already filled a JIRA issue for this:
https://issues.jenkins.io/browse/JENKINS-68806

From my point of view, I would not fix this that way. We should not do something different in PostgreSQL. I do not know why we started adding line in version table during postgresql upgrades, instead of just updating the only first created line. But in Postgresql, we must do like in other engines.

**Comment by kevinhuber** [comment]
Yeah, I see your point here, but i wasn't sure if the old SQL migrations could be modified in a way that won't break with peoples databases.
In my case there have been 4 rows in the table: `1`, `2`, `3`, `3` (yes, this was a duplicate already).
But at some point (nothing really changed) the db didn't returned the last row in the table (`4`) the first (`1`) instead.
I was caught in an endless loop where the plugin tried to apply patch `02` (without success as the indexes already existed).

I wasn't sure how consistent the order of the result-set ist on a PostreSQL Database is and if the old migrations could be rewritten in a style that allows the migration to be executed several times (as migration `03` for example - `CREATE INDEX IF NOT EXSISTS ...)).

But as all migrations after `01` only added or removed indexes this should be no problem.
I've updated the pr and modified the existing migrations in a way that allows them to be executed multiple times.
There's also a new migration that removes all rows in the version table and inserts a new single row with version `5`.
Since the `SELECT` from the `VERSIONS` table will always return a `version > 0` for existing databases, migration `01` is no candidate for multiple executions and doesn't have to be manipulated.

**Comment by bguerin** [comment]
Many thanks for your changes.

You are right, or at least, I think like you, existing migrations should not be changed after released because if we do that, we would end with unpredictable migration paths on the databases of our customer.
But like you said, it is "just" index creation / re-creation so it seems good (I thinked about multiple scenarios, they all pass. Hope I do not forget the one which fail ...)

**Review by bguerin — APPROVED** [review]

**Pull request merged**
