### PR TITLE
[JENKINS-44807] Don't forget to track the usage of the fingerprinted generated artifacts

### PR DESCRIPTION
**Pull request by cyrille-leclerc**
[JENKINS-44807](https://issues.jenkins-ci.org/browse/JENKINS-44807) Don't forget to track the usage of the fingerprinted generated artifacts.

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
I am not sure of the Fingerprint API, I am not sure that an artifact produced by a job should register itself in the usages of the artifact (`Fingerprint.addFor()`)

**Comment by justinbarry** [comment]
Good call.

**Comment by justinbarry** [comment]
What about going this route?
```java
            Fingerprint f = fingerprintMap.get(artifactMd5);
            if(f != null) {
                f.addFor(run);
            }
```

**Comment by cyrille-leclerc** [comment]
The Maven Job Type does it, let's do the same.

**Comment by justinbarry** [comment]
Interesting. Thanks.

**Pull request merged**
